#!/bin/bash
# Comprehensive fix script for rusty-db build errors

echo "=== Step 1: Fix struct field semicolons ==="
find /workspaces/rusty-db/src -name "*.rs" | while read file; do
    # Fix struct field semicolons -> commas (common error pattern)
    # Only fix inside struct definitions
    sed -i 's/: u64;$/: u64,/g' "$file"
    sed -i 's/: u32;$/: u32,/g' "$file"
    sed -i 's/: i64;$/: i64,/g' "$file"
    sed -i 's/: i32;$/: i32,/g' "$file"
    sed -i 's/: usize;$/: usize,/g' "$file"
    sed -i 's/: bool;$/: bool,/g' "$file"
    sed -i 's/: String;$/: String,/g' "$file"
    sed -i 's/: f64;$/: f64,/g' "$file"
    sed -i 's/: f32;$/: f32,/g' "$file"
done

echo "=== Step 2: Fix underscore variable references ==="

# Common patterns where underscore variables are used without underscore
patterns=(
    "_result:result"
    "_stats:stats"
    "_state:state"
    "_value:value"
    "_i:i"
    "_j:j"
    "_k:k"
    "_n:n"
    "_x:x"
    "_y:y"
    "_key:key"
    "_val:val"
    "_data:data"
    "_buf:buf"
    "_len:len"
    "_count:count"
    "_size:size"
    "_id:id"
    "_idx:idx"
    "_index:index"
    "_row:row"
    "_col:col"
    "_page:page"
    "_block:block"
    "_node:node"
    "_entry:entry"
    "_item:item"
    "_elem:elem"
    "_slot:slot"
    "_guard:guard"
    "_lock:lock"
    "_handle:handle"
    "_conn:conn"
    "_tx:tx"
    "_rx:rx"
    "_msg:msg"
    "_err:err"
    "_ret:ret"
    "_res:res"
    "_path:path"
    "_file:file"
    "_name:name"
    "_line:line"
    "_chunk:chunk"
    "_batch:batch"
    "_record:record"
    "_tuple:tuple"
    "_offset:offset"
    "_pos:pos"
    "_start:start"
    "_end:end"
    "_min:min"
    "_max:max"
    "_sum:sum"
    "_avg:avg"
    "_total:total"
    "_current:current"
    "_next:next"
    "_prev:prev"
    "_first:first"
    "_last:last"
    "_new:new"
    "_old:old"
    "_temp:temp"
    "_tmp:tmp"
    "_cache:cache"
    "_buffer:buffer"
    "_header:header"
    "_footer:footer"
    "_body:body"
    "_content:content"
    "_text:text"
    "_bytes:bytes"
    "_iter:iter"
    "_cursor:cursor"
    "_reader:reader"
    "_writer:writer"
    "_stream:stream"
    "_socket:socket"
    "_client:client"
    "_server:server"
    "_request:request"
    "_response:response"
    "_session:session"
    "_token:token"
    "_user:user"
    "_config:config"
    "_options:options"
    "_settings:settings"
    "_params:params"
    "_args:args"
    "_query:query"
    "_sql:sql"
    "_table:table"
    "_column:column"
    "_field:field"
    "_schema:schema"
    "_db:db"
    "_pool:pool"
    "_manager:manager"
    "_worker:worker"
    "_task:task"
    "_job:job"
    "_event:event"
    "_signal:signal"
    "_status:status"
    "_info:info"
    "_meta:meta"
    "_time:time"
    "_now:now"
    "_timestamp:timestamp"
    "_duration:duration"
    "_timeout:timeout"
    "_delay:delay"
    "_interval:interval"
    "_limit:limit"
    "_capacity:capacity"
    "_threshold:threshold"
    "_level:level"
    "_depth:depth"
    "_height:height"
    "_width:width"
    "_left:left"
    "_right:right"
    "_parent:parent"
    "_child:child"
    "_root:root"
    "_leaf:leaf"
    "_head:head"
    "_tail:tail"
    "_front:front"
    "_back:back"
    "_top:top"
    "_bottom:bottom"
    "_hash:hash"
    "_digest:digest"
    "_checksum:checksum"
    "_version:version"
    "_sender:sender"
    "_receiver:receiver"
    "_channel:channel"
    "_queue:queue"
    "_stack:stack"
    "_list:list"
    "_vec:vec"
    "_map:map"
    "_set:set"
    "_tree:tree"
    "_heap:heap"
    "_ring:ring"
    "_bit:bit"
    "_flag:flag"
    "_mode:mode"
    "_type:type"
    "_kind:kind"
    "_variant:variant"
)

find /workspaces/rusty-db/src -name "*.rs" | while read file; do
    for pattern in "${patterns[@]}"; do
        underscore_var="${pattern%%:*}"
        plain_var="${pattern##*:}"

        # Check if file has this pattern (uses _var in let but references var without _)
        if grep -q "let ${underscore_var}\b" "$file" && grep -q "\b${plain_var}\b" "$file"; then
            # Replace the let statement to use plain variable name
            sed -i "s/\blet ${underscore_var}\b/let ${plain_var}/g" "$file"
            sed -i "s/\blet mut ${underscore_var}\b/let mut ${plain_var}/g" "$file"
        fi
    done
done

echo "=== Step 3: Fix for loop underscore variables ==="

find /workspaces/rusty-db/src -name "*.rs" | while read file; do
    # Fix for _i in ... where i is used in the body
    for var in i j k n x y idx index; do
        if grep -q "for _${var} in" "$file" && grep -Pzo "for _${var} in[^}]+\b${var}\b" "$file" >/dev/null 2>&1; then
            sed -i "s/for _${var} in/for ${var} in/g" "$file"
        fi
    done
done

echo "=== Step 4: More specific fixes ==="

# Fix files with known patterns from error output
find /workspaces/rusty-db/src -name "*.rs" -exec grep -l "let _" {} \; | while read file; do
    # Generic fix: if we define _foo and use foo on a later line, rename _foo to foo
    # This is a simplified approach
    sed -i 's/let _\([a-z_][a-z0-9_]*\) =/let \1 =/g' "$file"
    sed -i 's/let mut _\([a-z_][a-z0-9_]*\) =/let mut \1 =/g' "$file"
done

echo "=== Done! ==="
echo "Run 'cargo check 2>&1 | head -50' to verify"
